version: '3.1'

services:
  redis:
    image: redis
    ports: ['6379:6379']
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

  server: &server
    depends_on: ["redis"]
    restart: on-failure:3
    tty: true
    build:
      context: .
    environment:
      - REDIS_URL=redis://redis/0
    ports: ["3000:3000"]
    volumes:
      - .:/rails

  test:
    <<: *server
    ports: []
    profiles: ["test"]
    environment:
      - REDIS_URL=redis://redis/1
    command: bin/rails test
